authors:
  nathalie:
    name: Nathalie
    description: Cyber and Data Manager | Legal Engineer | AI & Data Enthusiast | Blogger
    avatar: /assets/images/nathaliedecode_squared1_cables.png
    url: https://www.linkedin.com/in/nathalie-fouet/
  sebastien:
    name: Sebastien
    description: Tech Enthusiast | Digital Strategist | Blogger
    avatar: /assets/images/unknownuser_rounded1.png
    url: https://www.linkedin.com/in/sebastien-example/
  shannah:
    name: Shannah
    description: Data Scientist | AI Researcher | Blogger
    avatar: /assets/images/unknownuser_rounded1.png
    url: https://www.linkedin.com/in/shannah-example/
